Iter5
xdnv/ya-go-metrics pull request #2
Opened 2024-02-15 20:39 UTC by xdnv

2024-02-16 21:53 UTC, valentinsoe requested changes
Спасибо за работу.

В таком виде я пока не буду ее проверять. Тому есть две причины:
1) не пройдены тесты
2) PR явно не содержит все инкременты спринта.

Подготовь пожалуйста PR в котором будут все изменения данного спринта.

2024-02-19 22:02 UTC, valentinsoe requested changes
Спасибо за работу.
По порядку
1) надо переоформить PR, чтобы в diff были видны изменения не относительно какого-то предыдущего коммита, а относительно пустого репозитория
2) весь код написан фактически в 3-х файлах. Это делает его очень сложно читаемым.
3) подход с "общим"  разбором входящих значений для методов получения и обновления метрики только делает все сложнее.

У методов разный набор входящих параметров, сводя их к единому мы не получаем никакой пользы.

4) Сравнения через проверку на вхождение в массив это перебор:) Почему не сделать switch
 case "gauge": ....parseFloat
 case "counter": ... parseInt
 default: return UnsupportedTypeError?
 
Будет меньше кода и он будет проще:)
 
5) Если у нас есть интерфейс Metric, то почему наше хранилище MetricMap хранит в качестве значений любой интерфейс?

6) Процессы сбора метрик и их отправки - два отдельных процесса. Их не надо объединять в один.

7) В текущей реализации, каким будет PollCount на сервере спустя 40 секунд, если интервал отправки равен 10 секундам(и все операции проходят моментально)?

Для сейчас хватит. Пока рекомендую исправить то, что я написал. В следующей итерации проверки уже буду более детален(сейчас очень неудобно смотреть)

2024-02-19 22:02 UTC, valentinsoe commented on cmd/agent/config.go
> -//(4.1) Доработайте код, чтобы он умел принимать аргументы с использованием флагов.
Я проверю работу в таком виде, но впредь хотелось бы все изменения спринта видеть в PR.
Это явно diff с какой-то предыдущей версией:) Так лучше не делать, нужно собрать все изменения спринта в одном PR и не мержить промежуточные результаты в ветку main

2024-02-19 22:02 UTC, valentinsoe commented on cmd/agent/config.go
>  	if val, found := os.LookupEnv("ADDRESS"); found && (val != "") {
Проверка на пустую строку лишняя. С той точки зрения, что если некий человек запускающий агента задал переменную окружения, а в ней задал пустую строку - то это скорей всего ошибка и врядли он хотел запуститься с адресом по умолчанию.

То есть поведение приложения будет не очень "явным". Одно дело пользователь не задал значение, другое - он задал ошибочное.

2024-02-19 22:02 UTC, valentinsoe commented on cmd/agent/config.go
>  	if val, found := os.LookupEnv("ADDRESS"); found && (val != "") {
Не могу писать комментарии к строкам которые не входят в diff, но дальше такое же замечание как с пустой строкой. Если пользователь задал значение и опечатался - лучше такую ошибку не игнорировать применяя значение по умолчанию.

2024-02-19 22:02 UTC, valentinsoe commented on cmd/agent/main.go
> +		_, _ = io.Copy(io.Discard, resp.Body)
Можно в целом не читать, просто закрыть:)

2024-02-19 22:02 UTC, valentinsoe commented on cmd/agent/main.go
> +	"io"
Тоже не могу писать комментарии к конкретным строчкам:)

1) крипто-стойкий рандом нам тут не нужен, если от него отказаться, можно и с big не работать.
2) отправлять раз в reportInterval надо, а вот опрашивать надо раз в pollInterval, этого можно добиться 1 циклом.
3) сбор метрик и их отправка - разные процессы не надо их объединять в 1 функцию
4) рефлексией определять тип поля еще куда не шло, но это явный перебор, чтобы отправлять поля структуры. Проще завести map:)
5) NewMonitor - я бы ожидал что функция вернет мне структуру "монитор", а не запустит бесконечный процесс

2024-02-19 22:02 UTC, valentinsoe commented on cmd/server/main.go
>  	const pageTmpl = `<html>
Лучше большие константы не вносить в тело функции. Это позволит сделать функцию читаемой

2024-02-19 22:02 UTC, valentinsoe commented on cmd/server/main.go
> +	if r.URL.Path != "/" {
Роутер chi уже проверит это за нас, можно не писать доп. проверки

2024-02-19 22:02 UTC, valentinsoe commented on cmd/server/main.go
> +	mr.Mode = mode
Если убрать mode и не создавать подобный метод, то код будет короче и понятней:)

2024-02-19 22:02 UTC, valentinsoe commented on cmd/server/main.go
> +	// mr, err := extractMetricRequest(r.URL.Path)
Опять же не могу оставить комментарий прямо к коду.
Но проверять что метод POST не надо, за нас это уже делает роутер.

2024-02-20 12:09 UTC, xdnv commented on cmd/server/main.go
> +	if r.URL.Path != "/" {
Здесь проверка на входящие запросы вида /bla вместо /
В задании указано, что редиректы запрещены и под него написан отдельный тест.
Возможно, это как-то более красиво в chi делается.

2024-02-20 12:10 UTC, xdnv commented on cmd/server/main.go
> +	// mr, err := extractMetricRequest(r.URL.Path)
Убрал

2024-02-20 12:10 UTC, xdnv commented on cmd/agent/main.go
> +		_, _ = io.Copy(io.Discard, resp.Body)
Убрал

2024-02-20 12:11 UTC, xdnv commented on cmd/agent/config.go
> -//(4.1) Доработайте код, чтобы он умел принимать аргументы с использованием флагов.
Откатил main до исходного состояния, теперь diff должен показывать всё, что требуется

2024-02-20 15:46 UTC, xdnv commented on cmd/server/main.go
> +	mr.Mode = mode
Убрал подобный метод :)

2024-02-20 15:47 UTC, xdnv commented on cmd/server/main.go
>  	const pageTmpl = `<html>
Вынес константы из тела функции

2024-02-20 15:47 UTC, xdnv commented on cmd/agent/main.go
> +	"io"
1-5 - done

2024-02-20 15:49 UTC, xdnv commented on cmd/agent/config.go
>  	if val, found := os.LookupEnv("ADDRESS"); found && (val != "") {
Пример такой проверки не раз повторяется в обучающем материале ЯП, но согласен - неоднозначно. Заменил на panic() по итогам парсинга всех видов конфигурации, если таки умудрились удалить

2024-02-21 23:01 UTC, valentinsoe commented on cmd/server/main.go
> +	if r.URL.Path != "/" {
Так запрос типа /bla роутер в этот хендлер по идее и не "сроутит" :)
Я могу конечно ошибаться, во внутренностях chi не копался. Но думаю, что /bla ->  не будет смаршрутизирован в этот хендлер.

2024-02-21 23:31 UTC, valentinsoe requested changes
Спасибо за исправления.
Стало намного лучше. MetricRequest.Mode все еще остался, но теперь не используется.
Оформительские замечания - осталось много закомментированного кода и лишних пустых строк.
Сейчас не буду "мучать", но в следующем спринте надо разделить код не только на файлы, но и на пакеты(папки).

Не оформительские замечания.
1) Остался открытым вопрос с предыдущего ревью:
В текущей реализации, каким будет PollCount на сервере спустя 40 секунд, если интервал отправки равен 10 секундам(и все операции проходят моментально)?

2) Инициализация данных для тестов не должна быть в коде приложения. Она должна быть в коде тестов.

3) Новый подход к хранилищу и организации метрик. Он получился не совсем цельным. С одной стороны для получения метрик у нас есть "унифицированный" интерфейс, с другой для обновления - наш хендлер должен разбираться в типах метрик. А ведь эту логику можно "сгрузить" в хранилище.
Ну и желательно при хранении все-таки понимать каков тип метрики.

2024-02-21 23:31 UTC, valentinsoe commented on cmd/agent/config.go
> +	if val, found := os.LookupEnv("REPORT_INTERVAL"); found && (val != "") {
К агенту замечания про проверку на пустые значения применимы также как и к серверу в целом:)

2024-02-21 23:31 UTC, valentinsoe commented on cmd/agent/main.go
> +	Gauge   map[string]float64
Занудство.  Gauges и Counters

2024-02-21 23:31 UTC, valentinsoe commented on cmd/agent/main.go
> +	resp, err := PostValue(endpoint, metricType, metricName, fmt.Sprint(metricValue))
fmt.Sprint(merticValue) тут лишнее

2024-02-21 23:31 UTC, valentinsoe commented on cmd/agent/main.go
> +
Чисто оформительский вопрос, но глаз цепляет.
Пустая строка в начале функции "лишняя".

Я не против отделять значимые сегменты кода пустой строкой внутри фукнции. Но в начале и в конце это лишнее. Меньше кода влазит в экран.

2024-02-21 23:31 UTC, valentinsoe commented on cmd/agent/main.go
> +	wg.Add(1)
Запускаем две горутины, а в воркгруппу добавляем только 1. wg.Wait выполниться, когда сделает wg.Done любая из них.
Пока не принципиально, но в будущем может привести к неожиданным эффектам.

2024-02-21 23:31 UTC, valentinsoe commented on cmd/server/main.go
> +	// это пойдёт в тесты
Инициализация данных для тестов должна быть в тестах, а не в "продакшен" коде.

2024-02-22 05:30 UTC, xdnv commented on cmd/agent/main.go
> +	Gauge   map[string]float64
Сначала так и сделал, потом подумал про reflection. Вернул множественные.

2024-02-22 05:31 UTC, xdnv commented on cmd/agent/main.go
> +
Согласен, убрал пустые строки в начале и в конце.

2024-02-22 05:32 UTC, xdnv commented on cmd/agent/main.go
> +	wg.Add(1)
Я это ошибочно прочёл как "номер" группы, а не число участников. Поправил на фактическое число участников - 2.

2024-02-22 06:10 UTC, xdnv commented on cmd/server/main.go
> +	if r.URL.Path != "/" {
И, тем не менее, физически роутит. В рамках следующих спринтов буду подробней смотреть внутреннюю кухню.

2024-02-22 06:19 UTC, xdnv commented
> 1. Остался открытым вопрос с предыдущего ревью:
>    В текущей реализации, каким будет PollCount на сервере спустя 40 секунд, если интервал отправки равен 10 секундам(и все операции проходят моментально)?

Как понимаю, одним из подводных камней задания является инкремент счётчика, отличный от числа отправок данных.
В исходной реализации с одной функцией опроса и отправки Poll count за сорок секунд был бы равен четырём.
После разделения Poll Count будет обновляться с периодичностью опроса, то есть за 40 секунд будет PollCount=20.
Это, опять же, при идеальных условиях нулевых задержек отправки данных.

2024-02-22 06:27 UTC, xdnv commented on cmd/agent/config.go
> +	if val, found := os.LookupEnv("REPORT_INTERVAL"); found && (val != "") {
Добавил проверку на нулевое значение с паникой, поменял местами порядок инициализации (сначала poll, потом report)

2024-02-22 06:30 UTC, xdnv commented on cmd/agent/main.go
> +	resp, err := PostValue(endpoint, metricType, metricName, fmt.Sprint(metricValue))
Следствие рефакторинга, убрал

2024-02-22 10:16 UTC, xdnv commented on cmd/server/main.go
> +	// это пойдёт в тесты
Вынес тесты в storage_test.go

2024-02-22 11:03 UTC, xdnv commented
> 3\. Новый подход к хранилищу и организации метрик. Он получился не совсем цельным. С одной стороны для получения метрик у нас есть "унифицированный" интерфейс, с другой для обновления - наш хендлер должен разбираться в типах метрик. А ведь эту логику можно "сгрузить" в хранилище.
>     Ну и желательно при хранении все-таки понимать каков тип метрики.

Добавил метод хранилища storage.UpdateMetricS() для единообразного создания/обновления любого типа метрики внутри хранилища. Хендлер теперь ничего не знает о типах кроме передаваемого ему параметра.
Также добавил в интерфейс метрики метод GetType(), возвращающий строковый тип метрики

2024-02-22 11:21 UTC, xdnv commented
> Оформительские замечания - осталось много закомментированного кода и лишних пустых строк.

Все ненужные комментарии почищены, лишние строки тоже теперь не с нами

2024-02-22 21:47 UTC, valentinsoe approved these changes
Спасибо за исправления.
Работу принимаю. Дальнешими оформительскими и архитектурными улучшениями займемся в следующем спринте.

2024-02-22 22:30 UTC, merged