Iter9
xdnv/ya-go-metrics pull request #3
Opened 2024-02-27 16:17 UTC by xdnv

2024-03-04 22:35 UTC, valentinsoe requested changes
Привет! Спасибо за работу.
Извиняюсь за срок проверки.

1) Не надо заводить в каждом пакете go.mod и go.sum. Достаточно 1 пары файлов на весь модуль.
2) Сервер не умеет принимать сжатые запросы(нигде не нашел кода, отвечающего за распаковку)

2024-03-04 22:35 UTC, valentinsoe commented on cmd/agent/main.go
> +func collector(ac app.AgentConfig, ctx context.Context, wg *sync.WaitGroup) {
Контекст принято передавать первым параметром.

2024-03-04 22:35 UTC, valentinsoe commented on cmd/agent/main.go
> +	defer cancel()
defer cancel() нам кажется уже не нужен - до него будет либо паника, либо вызовется cancel с 240 строки

2024-03-04 22:35 UTC, valentinsoe commented on cmd/agent/main.go
> +	// shut down gracefully with timeout of 5 seconds max
Зачем создается контекст, который никуда не передается и мы только его отменяем(после того, как дождались завершения переданного в функцию контекста?)

2024-03-04 22:35 UTC, valentinsoe commented on internal/adapters/logger/go.mod
> +module logger
Если нет цели распространять данный logger как отдельный пакет - не надо ему создавать отдельные go.mod/go.sum

2024-03-04 22:35 UTC, valentinsoe commented on internal/adapters/logger/zap.go
> +	enccoderConfig := zap.NewDevelopmentEncoderConfig()
Удвоенная "с" лишняя

2024-03-04 22:35 UTC, valentinsoe commented on internal/ports/storage.go
> +package ports
Не понимаю, почему пакет называется ports - о каких портах речь?

2024-03-04 22:46 UTC, xdnv commented
> 2\. Сервер не умеет принимать сжатые запросы(нигде не нашел кода, отвечающего за распаковку)

Умеет, я активировал штатную функциональность chi через **mux.Use(middleware.Compress(5))** (стр. 98 main.go)
Тесты на компрессию агента/сервера ЯП проходят. Если нужно именно свою обёртку компрессии написать -- дай, пожалуйста, знать.

2024-03-04 22:55 UTC, xdnv commented
> 1. Не надо заводить в каждом пакете go.mod и go.sum. Достаточно 1 пары файлов на весь модуль.

Без них получаю ошибки вида
main.go:15:2: module ./internal/adapters/logger: reading ..\..\internal\adapters\logger\go.mod: open *\ya-go-metrics\internal\adapters\logger\go.mod: The system cannot find the file specified.
handle_request.go:8:2: module ./internal/domain: reading ..\..\internal\domain\go.mod: open *\ya-go-metrics\internal\domain\go.mod:
 The system cannot find the file specified.

Также в корне использую конструкции вида replace internal/app => ./internal/app.
Т.к. корневая папка проекта не соотнесена с $GOPATH по техническим и идеологическим причинам, без go.mod в подмодулях проект не соберётся.

2024-03-04 22:55 UTC, xdnv commented on internal/adapters/logger/go.mod
> +module logger
Т.к. корневая папка проекта не соотнесена с $GOPATH по техническим и идеологическим причинам, без go.mod в подмодулях проект не соберётся.
Других вариантов без использования GOPATH я (пока) не знаю.

2024-03-04 22:56 UTC, xdnv commented on cmd/agent/main.go
> +	// shut down gracefully with timeout of 5 seconds max
Модули не видят контекст приложения, в дальнейшем планирую через него передавать структуры конфигурации и т.п.

2024-03-04 22:57 UTC, xdnv commented on internal/adapters/logger/zap.go
> +	enccoderConfig := zap.NewDevelopmentEncoderConfig()
Исправил

2024-03-04 23:04 UTC, xdnv commented on cmd/agent/main.go
> +func collector(ac app.AgentConfig, ctx context.Context, wg *sync.WaitGroup) {
Поправил

2024-03-04 23:10 UTC, xdnv commented on internal/ports/storage.go
> +package ports
Это попытка в приближение к Hexagonal архитектуре приложения, которую нам показывали на скринкасте.
Пока что чистый карго культ, согласен.
Порты как точки взаимодействия с другими модулями программы и внешним миром.
![image](https://github.com/xdnv/ya-go-metrics/assets/62163079/7f9389b9-038f-4fcb-9051-bf21ed4e093c)

2024-03-04 23:18 UTC, xdnv commented on cmd/agent/main.go
> +	defer cancel()
Я при добавлении исходил из того, что контекст используется для управляемого завершения всех запущенных горутин, и при любой модификации модуля (которых будет ещё немало) должен гарантированно закрываться при выходе из main().
Если это "плохой" паттерн go разработки, дай знать -- удалю строку.

2024-03-04 23:21 UTC, xdnv commented on cmd/agent/main.go
> +	// shut down gracefully with timeout of 5 seconds max
Сейчас используется для управляемого graceful shutdown и в агенте, и в сервере. Выход по Ctrl+C отрабатывается в моём коде отражается в консоли, процесс не выходит молча по дефолту.

2024-03-04 23:43 UTC, valentinsoe commented on cmd/agent/main.go
> +	defer cancel()
Паттерн правильны, если мы не хотим дождаться завершения "отменяемых" горутин. Если же хотим дождаться -  все равно придется явно вызвать cancel и отдельным кодом дождаться, что горутины действительно завершились.
В функции main в defer cancel() смысла нет. Когда закончится main - все горутины будут насильно "закончены" все равно:)

2024-03-04 23:48 UTC, valentinsoe commented on internal/adapters/logger/go.mod
> +module logger
$GOPATH не прибит гвоздями, его можно менять.

2024-03-04 23:57 UTC, valentinsoe requested changes
Ответил на комментарии. С  go.mod бог с ним, но не располагать код в GOPATH -> придумывать себе проблемы:)
Про сжатие:
Во-первых мидлвара chi compress -> сжимает ответы. Но не "расжимает" запросы от клиента. Тесты это не покрывают. 
Во-вторых она не настроена так, как написано в задании.

Пробо

2024-03-04 23:57 UTC, valentinsoe commented on cmd/agent/main.go
> +	// shut down gracefully with timeout of 5 seconds max
Контекст в функции main -> используется для graceful shutdown.
Этот же контекст - используется никак:)

2024-03-04 23:57 UTC, valentinsoe commented on internal/ports/storage.go
> +package ports
Мое отношение - ports может быть папкой в пути к пакету, но не пакетом.
Ну то есть ports/storage -> понятно что значит. А сам по себе ports - очень плохо обозначает назначение пакета.

2024-03-05 01:05 UTC, xdnv commented
Ports: согласен, заменил на ports/storage
Контекст: ну в смысле никак? Все запускаемые горутины по нему отслеживают сигнал прерывания работы и сами, по хорошему, завершаются.
_```
2024-03-05T04:03:54     INFO    srv: using endpoint localhost:8080
2024-03-05T04:03:54     INFO    srv: datafile .\log.json
srv: received ^C - shutting down
srv: telling goroutines to stop
srv-dumper: stop requested
2024-03-05T04:03:56     INFO    srv: shutdown requested
Listen: http: Server closed
srv: server stopped
srv: shutdown
```_

2024-03-05 03:44 UTC, xdnv commented
> Во-первых мидлвара chi compress -> сжимает ответы. Но не "расжимает" запросы от клиента. Тесты это не покрывают. Во-вторых она не настроена так, как написано в задании.

Настроил типы контента по заданию, добавил обработку сжатых запросов.

2024-03-05 07:59 UTC, valentinsoe requested changes
Все еще. Контекст который создается и отменяется в фунции agent лишний.
Весь gracefull shutown построен на контексте созданном на строчке 220.

2024-03-05 07:59 UTC, valentinsoe commented on cmd/agent/main.go
> +	// shut down gracefully with timeout of 5 seconds max
Я все еще настраиваю что вот этот контекст на 264 строчке никак не используется и лишний.
Gracefull shutdown весь в функции main и используется контекст созданный на строчке 220ю

2024-03-05 08:17 UTC, xdnv commented
> Все еще. Контекст который создается и отменяется в фунции agent лишний.
> Весь gracefull shutown построен на контексте созданном на строчке 220.

Понял, увидел, согласен. Эта логика нужна на сервере для ожидания завершения уже выполняющихся дел веб-серверных, на агенте в текущем виде -- да, лишнее. Убрал.

2024-03-05 15:43 UTC, valentinsoe approved these changes
Ура! Мы сошлись во мнении про лишний контекст.

2024-03-05 18:07 UTC, merged