Iter13
xdnv/ya-go-metrics pull request #4
Opened 2024-03-12 14:58 UTC by xdnv

2024-03-18 22:52 UTC, valentinsoe requested changes
Спасибо за работу.
В 13 инкременте задание подразумевает обобщенный подход к повторам при ошибках.
И повтор записи в базу гораздо важнее повтора отправки метрик(они итак отправятся в следующий pollInterval).

2024-03-18 22:52 UTC, valentinsoe commented on cmd/agent/main.go
> +func PostValueRetriable(ac app.AgentConfig, body *bytes.Buffer) (*http.Response, error) {
Рекомендую подумать, как сделать универсальный механизм retry любой функции. А не вшивать логику в конкретную реализацию.

2024-03-18 22:52 UTC, valentinsoe commented on cmd/server/handle_ping.go
> +	_, _ = w.Write([]byte(body))
В таком случае левую часть можно просто не писать

2024-03-18 22:52 UTC, valentinsoe commented on cmd/server/handle_updates.go
> +		err := stor.UpdateMetricS(mr.Type, mr.Name, mr.Value)
Кажется можно сделать это 1 запросом в БД(ну или двумя отдельно Counters, отдельно Gauge)

2024-03-18 22:52 UTC, valentinsoe commented on cmd/server/handle_updates.go
> +			return
Если не удалось обновить 1 метрику, это кажется не повод, не обновить остальные пришедшие в батче.
А еще лучше обновить все или ничего(в случае с БД)

2024-03-18 22:52 UTC, valentinsoe commented on cmd/server/main.go
> +
Рекомендую убрать эту функцию из main. Кажется ей тут совсем не место.

2024-03-18 22:52 UTC, valentinsoe commented on cmd/server/main.go
> +		var safeDSN = strings.Split(sc.DatabaseDSN, " ")
Регулярным выражением выглядело бы немного проще

2024-03-18 22:52 UTC, valentinsoe commented on internal/ports/storage/db.go
> +			DO UPDATE SET value = excluded.value;
Значение счетчиков долно складываться, не только в следующей функции, но и в этой.

2024-03-19 00:00 UTC, xdnv commented on internal/ports/storage/db.go
> +			DO UPDATE SET value = excluded.value;
Это "техническая" функция, аналогичная загрузке набора метрик из файла в память. В ней я оставил возможность инициализировать базу данных именно слепком значений переданных реплик. Возможно, нужно какое-то документирование на этот счёт?

2024-03-19 00:14 UTC, xdnv commented on cmd/server/handle_ping.go
> +	_, _ = w.Write([]byte(body))
Согласен, убрал

2024-03-19 00:15 UTC, xdnv commented on cmd/server/main.go
> +		var safeDSN = strings.Split(sc.DatabaseDSN, " ")
Как вижу, DSN-строку подсистема понимает и в виде ключей, и в виде URI ('postgresql://localhost/postgres?sslmode=verify-full'). Видимо, надо оба добавлять, раз уже начал.

2024-03-19 00:45 UTC, xdnv commented on cmd/server/main.go
> +
Не разобрался поначалу с replace, она не видела другие пакеты в internal. Поправил.

2024-03-19 18:08 UTC, xdnv commented on cmd/server/main.go
> +		var safeDSN = strings.Split(sc.DatabaseDSN, " ")
Заменил на regex

2024-03-19 21:45 UTC, xdnv commented on cmd/agent/main.go
> +func PostValueRetriable(ac app.AgentConfig, body *bytes.Buffer) (*http.Response, error) {
Добавил повторы, обработка повторяемых ошибок идёт в отдельных функциях для БД и Веба.

С вебом выявил большую засаду: линтер, проверяющий закрытие Body ни в какую не хочет работать с замкнутой переменной результата, хочет явное закрытие тела во внутренней переменной функции.
Судя по гуглению, я такой не один.

2024-03-19 22:27 UTC, xdnv commented on cmd/agent/main.go
> +func PostValueRetriable(ac app.AgentConfig, body *bytes.Buffer) (*http.Response, error) {
Для повторов БД добавил класс ошибок pgerrcode.IsConnectionException(). В задании требования логики по детальным классам ошибок не описываются, а самостоятельно их разбирать весьма трудоёмко. Сдаётся мне, что достаточно показать умение с ними работать.

2024-03-19 23:11 UTC, xdnv commented on cmd/server/handle_updates.go
> +			return
Добавил сбор всех встреченных ошибок обработки пакета метрик в массив. Далее эти ошибки выводятся в тело HTTP ответа.

2024-03-20 00:41 UTC, xdnv commented on cmd/server/handle_updates.go
> +		err := stor.UpdateMetricS(mr.Type, mr.Name, mr.Value)
Завернул обновление метрик в транзакцию.
Я умею генерировать тексты пакетных запросов, но сейчас уже откровенно не в состоянии креативить это на новом языке. Если это не является жёстким требованием спринта, предлагаю оставить на последующие оптимизации.
Ну и более детальные ошибки будут в случае чего.

2024-03-21 10:13 UTC, valentinsoe commented on cmd/agent/main.go
> +func PostValueRetriable(ac app.AgentConfig, body *bytes.Buffer) (*http.Response, error) {
Да, есть такое неудобство с этим линтером.
Что могу добавить:

resp = bresp
bresp.Body.Close()

На самом деле ты оба тела закрыл. Потому bresp и resp указатели:)

Чтобы все это обойти. Можно в этой же анонимной функции тело и читать(если оно нам вообще нужно). И возвращать его наружу уже прочтенное.

2024-03-21 10:13 UTC, valentinsoe approved these changes
Спасибо за исправления!
Требований делать обновление батч-запросом в БД нет, это было просто предложение к улучшению.

Про закрытие тела ответа - дописал комментарий

2024-03-21 10:36 UTC, xdnv commented on cmd/agent/main.go
> +func PostValueRetriable(ac app.AgentConfig, body *bytes.Buffer) (*http.Response, error) {
да, я примерно из этого и исходил: подсунул ему локальный указатель, а тело мне в конкретном кейсе не нужно, поэтому закрыл его ультимативно.
Похоже, в замыканиях с http.Request придётся городить свои структуры передачи тела и закрывать сразу. или отключать линтер для строки (как понимаю, в текущем проекте это недоступно).

2024-03-21 10:39 UTC, merged