Iter15
xdnv/ya-go-metrics pull request #7
Opened 2024-03-22 13:59 UTC by xdnv

Сначала сделал 15й PR, т.к. из текста задания не ясно, что оба инкремента должны быть в 14-м, там 14 и 15 инкременты указаны. Но на 15й нет тестов.
Это уже починенная и выровненная (hope so) версия.

2024-03-22 16:53 UTC, xdnv commented
Судя по коду автотестов, iter14 только передаёт серверу ключ для подписи, а вот сам хеш не вычисляет и не передаёт. Пришлось реализацию отклонить от ТЗ и делать вместо отбойника предупреждение, если ключ не совпадает.

2024-03-25 23:01 UTC, valentinsoe commented
> Сначала сделал 15й PR, т.к. из текста задания не ясно, что оба инкремента должны быть в 14-м, там 14 и 15 инкременты указаны. Но на 15й нет тестов. Это уже починенная и выровненная (hope so) версия.

Как раз наоборот оба инкремента должны быть в 15-м. И на него нет тестов:)

2024-03-25 23:07 UTC, valentinsoe requested changes
Спасибо за работу
Во-первых не вижу кода 15 инкеремента.
Во-вторых неудачная проверка подписи должна приводить к ошибке(400 bad request)

2024-03-25 23:07 UTC, valentinsoe commented on cmd/server/main.go
> +			//this should and WILL be done in production
В задании указано, что надо сделать если подпись не совпала - вернуть 400 (bad request)

2024-03-25 23:07 UTC, valentinsoe commented on cmd/server/main.go
> +func handleSignedRequests(next http.Handler) http.Handler {
Это вполне обычная мидлвара, почему она в main оказалась?:)

2024-04-01 16:12 UTC, xdnv commented
> Как раз наоборот оба инкремента должны быть в 15-м. И на него нет тестов:)

рукалицо :)

2024-04-02 10:04 UTC, xdnv commented on cmd/server/main.go
> +func handleSignedRequests(next http.Handler) http.Handler {
Перенёс в пакет работы с подписями
Также ключ теперь хранится не в самом приложении, а в скрытом объекте пакета, работающего с подписями

2024-04-02 10:04 UTC, xdnv commented on cmd/server/main.go
> +			//this should and WILL be done in production
Верну после переноса всего этого благолепия в 15 итерацию. Это уже было реализовано, смутило падение на тестах.

2024-04-03 06:49 UTC, closed without merging