Iter15
xdnv/ya-go-metrics pull request #8
Opened 2024-04-03 06:52 UTC by xdnv

2024-04-03 07:08 UTC, xdnv commented
Перенёс все изменения в iter15, реализовал логику задачи кроме канала-конвейера и rate limit.

2024-04-05 23:34 UTC, valentinsoe requested changes
Спасибо за работу.
В целом к написанному у меня претензий нет, и я понимаю, что задание 15 инкремента звучит "натянуто", но рейт-лимитер и сбор метрик в отдельной горутине не реализованы:)

2024-04-05 23:34 UTC, valentinsoe commented on cmd/agent/main.go
> +			vm, err := mem.VirtualMemory()
Этот коллектор просили запустить в отдельной горутине в задании.

2024-04-09 22:42 UTC, valentinsoe approved these changes
Спасибо за исправления!

2024-04-10 02:28 UTC, merged